name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GO_VERSION: "1.25"
  TERRAFORM_VERSION: "1.8.5"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Go tests
        env:
          GOCACHE: ${{ github.workspace }}/.cache/go-build
        run: go test ./...

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    env:
      TF_VAR_project_id: example-project
      TF_VAR_image: us-central1-docker.pkg.dev/example-project/cloud-run-blog/app:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color
