name: Deploy
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

env:
  GO_VERSION: "1.25"
  SERVICE_NAME: cloud-run-blog
  REGION: asia-northeast1
  IMAGE: ${{ secrets.ARTIFACT_REPOSITORY }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push image
        id: cloudbuild-submit
        run: |
          BUILD_ID=$(gcloud builds submit \
            --project "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" \
            --region "${{ env.REGION }}" \
            --tag "${{ env.IMAGE }}" \
            --async \
            --format='value(metadata.build.id)')
          if [ -z "$BUILD_ID" ]; then
            echo "Failed to obtain Cloud Build ID." >&2
            exit 1
          fi
          echo "build_id=$BUILD_ID" >> "$GITHUB_OUTPUT"
          echo "Triggered Cloud Build: $BUILD_ID"

      - name: Wait for Cloud Build
        run: |
          BUILD_ID="${{ steps.cloudbuild-submit.outputs.build_id }}"
          if [ -z "$BUILD_ID" ]; then
            echo "Cloud Build ID missing." >&2
            exit 1
          fi
          echo "Waiting for Cloud Build $BUILD_ID..."
          while true; do
            STATUS=$(gcloud builds describe "$BUILD_ID" \
              --project "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" \
              --region "${{ env.REGION }}" \
              --format="value(status)")
            case "$STATUS" in
              SUCCESS)
                echo "Cloud Build $BUILD_ID succeeded."
                break
                ;;
              QUEUED|WORKING)
                sleep 10
                ;;
              *)
                echo "Cloud Build $BUILD_ID failed with status: $STATUS" >&2
                gcloud builds describe "$BUILD_ID" \
                  --project "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" \
                  --region "${{ env.REGION }}" \
                  --format="yaml"
                exit 1
                ;;
            esac
          done

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ env.SERVICE_NAME }}" \
            --project "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}" \
            --region "${{ env.REGION }}" \
            --image "${{ env.IMAGE }}" \
            --allow-unauthenticated
